### ISSUE TITLE
Using image magic engine doesn't work

### ISSUE THREAD

**Issue by Dan503** [davidtheclark/grunt-spritesmith-hd#13]
Error in grunt:
http://grabilla.com/05206-61966a8f-68d5-4d75-a7f8-b3dd959875c1.png

My grunt code:
http://grabilla.com/05206-1835735c-4c78-4f6c-8a38-d6387caa5618.png

It looks like it tried to switch to using the gm engine instead of the im engine for some reason :/

I've installed both engines on my computer now though and I'm still getting that message :(

I tried going doing the resizing with the gm engine and it's still not working for me :(

**Comment by benib** [comment]
From the output you posted it looks like the resizing actually worked.
grunt-spritesmith-hd is really only doing the resizing and then passes to grunt-spritesmith to actually do the spriting for the now two sets of images. grunt-spritesmith-hd creates a folder `tempAssets` in your project directory where it puts the resized assets for this.
So the option `resizeEngine` only defines what to use for resizing the images. This is not necessarily the same engine used for spriting.
Could you check, if this folder tempAssets exists and actually contains the resized assets within a subfolder?

If you have these resized images, please try to set the engine for grunt-spritesmith (used for the actual sprite generation) through the `engine` option of grunt-spritesmith-hd. This option is directly passed to grunt-spritesmith and defaults to `gm` (can be one of auto, phantomjs, canvas, gm, pngsmith). Please be aware that grunt-spritesmith-hd uses quite an old version of grunt-spritesmith (1.26.0).

**Comment by Dan503** [comment]
I ended up taking a different approach. I used a combination of grunt-spritesmith and grunt-image-resize to create the HD auto-sprite. That way I could use the latest version of grunt-spritesmith... and I could actually get it working. I don't really want to try and go back to this now.

Wouldn't the bug be that you define im as the engine for HD spritesmith but that command isn't getting parsed into regular spritesmith? So if you set the resize engine to im in HD spritesmith it should automatically set regular spritesmith to use the im engine as well.

**Comment by benib** [comment]
Glad you found a working setup.
As for the mapping of resize engine and spriting engine: I don't fully agree here, as grunt-spritesmith-hd can only work with graphicsmagick or imagemagick, whereas grunt-spritesmith supports more engines. Only mapping in certain circumstances where you define an engine that is supported by both is weird.

I'm going to close this issue for now.
